djlearn/djlearn/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from . import views

urlpatterns = [
    path('polls/', include('polls.urls'), name='polls'),
    path('admin/', admin.site.urls, name='admin'),
    path('todo/', include('todo.urls'), name='todo'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('', views.index, name='index'),
]

if not settings.TESTING:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()

djlearn/todo/urls.py
from django.urls import path

from . import views

app_name = "todo"
urlpatterns = [
    path('', views.index, name='index'),
    path('todolist/<int:pk>/', views.todolist, name='todolist'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('user/', views.user_redirect, name='user_redirect'),
    path('user/<int:pk>/', views.user, name='user'),
    path('team/<int:pk>/', views.team, name='team'),
    path('signup/', views.signup, name='signup'),
    path('update/<str:action>/', views.update, name='update'),
]

djlearn/todo/models.py
from django.db import models

# Create your models here.
class Todo_User(models.Model):
    username = models.CharField(max_length=50)
    display_name = models.CharField(max_length=50)
    friends = models.ManyToManyField('self')
    friend_perms = models.CharField(max_length=1,choices={
        "P": "None",
        "V": "View",
        "M": "Modify"
    }, default="V")
    everyone_perms = models.CharField(max_length=1,choices={
        "P": "None",
        "V": "View",
        "M": "Modify"
    }, default="P")
    friend_requests = models.ManyToManyField('self', symmetrical=False)

    def __str__(self):
        return self.username
    
class Team(models.Model):
    name = models.CharField(max_length=50, unique=True)
    members = models.ManyToManyField(Todo_User, related_name='team_members')
    leaders = models.ManyToManyField(Todo_User, related_name='team_leaders')

    def __str__(self):
        return self.name
    
class TodoItem(models.Model):
    user = models.ForeignKey(Todo_User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True)
    description = models.CharField(max_length=200, blank=True)
    completed = models.BooleanField(default=False)
    assigned = models.BooleanField(default=False)
    category = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

djlearn/todo/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from accounts.views import SignUpView
from .models import Todo_User, TodoItem, Team

# Create your views here.

def index(request):
    return render(request, 'todo/index.html', {'todo_user': Todo_User.objects.get(username=request.user.username) if request.user.is_authenticated else None})

def todolist(request, pk):
    user = get_object_or_404(Todo_User, pk=pk)
    perms = user.everyone_perms
    if request.user.is_authenticated:
        self = get_object_or_404(Todo_User, username=request.user.username)
        if self == user:
            perms = 'M'
        elif self in user.friends.all():
            match user.friend_perms:
                case 'V':
                    if perms != 'M':
                        perms = 'V'
                case 'M':
                    perms = 'M'
    if perms == 'P':
        return HttpResponse("You do not have permission to view this user's todo list.", status=403)
    todo_items = user.todoitem_set.order_by('id')
    categories = Team.objects.filter(members=user).order_by('name')
    if categories.exists():
        categorized = []
        for category in categories:
            items_in_category = todo_items.filter(category=category)
            if items_in_category.exists():
                categorized.append({'name': category.name, 'todo_items': items_in_category, 'modify': True})
        uncategorized_items = todo_items.filter(category__isnull=True)
        if uncategorized_items.exists():
            categorized.append({'name': 'Uncategorized', 'todo_items': uncategorized_items, 'modify': True if perms == 'M' else False})
        return render(request, 'todo/todolist.html', {'user': user, 'categories': categorized})
    else:
        return render(request, 'todo/todolist.html', {'user': user, 'categories': [{'name': 'Uncategorized', 'todo_items': todo_items, 'modify': True if perms == 'M' else False}]})

def check_modify_permission(user, self):
    if self == user:
        return True
    elif user.everyone_perms == 'M':
        return True
    elif self in user.friends.all() and user.friend_perms == 'M':
        return True
    return False
def update(request, action) -> HttpResponse | HttpResponseRedirect:
    # CSRF validation does not like any methods that aren't POST, so I just use that for everything
    if request.method == 'POST':
        user = get_object_or_404(Todo_User, username=request.user.username) if request.user.is_authenticated else None
        if action == 'toggle':
            try:
                item_id = int(request.POST["item_id"])
                item = get_object_or_404(TodoItem, pk=item_id)
                if not check_modify_permission(item.user, user):
                    return HttpResponse("You do not have permission to modify this user's todo list.", status=403)
                item.completed = not item.completed
                item.save()
                return HttpResponse("Item updated successfully", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid item ID", status=400)
        elif action == 'edit':
            try:
                item_id = int(request.POST["item_id"])
                item = get_object_or_404(TodoItem, pk=item_id)
                if not check_modify_permission(item.user, user):
                    return HttpResponse("You do not have permission to modify this user's todo list.", status=403)
                item.name = request.POST['name']
                item.description = request.POST['description']
                item.save()
                return HttpResponse("Item edited successfully", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'add':
            try:
                user_id = int(request.POST["user_id"])
                item_user = get_object_or_404(Todo_User, pk=user_id)
                if not check_modify_permission(item_user, user):
                    return HttpResponse("You do not have permission to modify this user's todo list.", status=403)
                category_id = int(request.POST["category_id"])
                name = request.POST['name']
                description = request.POST['description']
                new_item = TodoItem(user=item_user, name=name, description=description, category=Team.objects.get(pk=category_id) if category_id != -1 else None)
                new_item.save()
                return HttpResponse("Item added successfully", status=201)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'delete':
            try:
                item_id = int(request.POST['item_id'])
                item = get_object_or_404(TodoItem, pk=item_id)
                if not check_modify_permission(item.user, user):
                    return HttpResponse("You do not have permission to modify this user's todo list.", status=403)
                item.delete()
                return HttpResponse("Item deleted successfully", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid item ID", status=400)
        elif action == 'deleteUser':
            try:
                user_id = int(request.POST['user_id'])
                delete_user = get_object_or_404(Todo_User, pk=user_id)
                if not delete_user == user:
                    return HttpResponse("Can only delete self", status=403)
                delete_user.delete()
                return HttpResponseRedirect(reverse('todo:index'))
            except (KeyError, ValueError):
                return HttpResponse("Invalid user ID", status=400)
        elif action == 'addFriend':
            try:
                friend_name = request.POST['friend_name']
                friend = get_object_or_404(Todo_User, username=friend_name)
                if friend == user:
                    return HttpResponse("Cannot add yourself as a friend", status=400)
                if friend in user.friends.all():
                    return HttpResponse("Already friends", status=400)
                if user in friend.friend_requests.all():
                    return HttpResponse("Friend request already sent", status=400)
                friend.friend_requests.add(user)
                friend.save()
                return HttpResponse("Friend request sent", status=201)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'acceptFriend':
            try:
                friend_id = int(request.POST['friend_id'])
                friend = get_object_or_404(Todo_User, pk=friend_id)
                if friend not in user.friend_requests.all():
                    return HttpResponse("No friend request from this user", status=400)
                user.friends.add(friend)
                user.friend_requests.remove(friend)
                user.save()
                return HttpResponse("Friend request accepted", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'removeFriend':
            try:
                friend_id = int(request.POST['friend_id'])
                friend = get_object_or_404(Todo_User, pk=friend_id)
                if friend not in user.friends.all():
                    return HttpResponse("Not friends with this user", status=400)
                user.friends.remove(friend)
                user.save()
                return HttpResponse("Friend removed", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'declineFriend':
            try:
                friend_id = int(request.POST['friend_id'])
                friend = get_object_or_404(Todo_User, pk=friend_id)
                if friend not in user.friend_requests.all():
                    return HttpResponse("No friend request from this user", status=400)
                user.friend_requests.remove(friend)
                user.save()
                return HttpResponse("Friend request declined", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'cancelFriendRequest':
            try:
                friend_id = int(request.POST['friend_id'])
                friend = get_object_or_404(Todo_User, pk=friend_id)
                if user not in friend.friend_requests.all():
                    return HttpResponse("No sent friend request to this user", status=400)
                friend.friend_requests.remove(user)
                friend.save()
                return HttpResponse("Friend request canceled", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'setFriendPerms':
            try:
                perms = request.POST['perms']
                if perms not in ['P', 'V', 'M']:
                    return HttpResponse("Invalid permissions value", status=400)
                user.friend_perms = perms
                user.save()
                return HttpResponse("Friend permissions updated", status=200)
            except (KeyError, ValueError):
                return HttpResponse("Invalid data provided", status=400)
        elif action == 'setEveryonePerms':
            try:
                perms = request.POST['perms']
                if perms not in ['P', 'V', 'M']:
                    return HttpResponse("Invalid permissions value", status=400)
                user.everyone_perms = perms
                user.save()

djlearn/todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>To-do Lists</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'todo/styles.css' %}">
        <script src="{% static 'todo/init.js' %}"></script>
        {% if user.is_authenticated %}
        <script>
            window.location.href = "{% url 'todo:user' todo_user.id %}";
        </script>
        {% endif %}
    </head>
    <body>
        <h1>Welcome to the To-do app!</h1>
        <button onclick="window.location.href='{% url 'login' %}'">Log In</button>
        <button onclick="window.location.href='{% url 'password_reset' %}'">Forgot Password</button>
        <button onclick="window.location.href='{% url 'signup' %}'">Sign Up</button>
    </body>
</html>

djlearn/todo/templates/todo/template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>template</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'todo/styles.css' %}">
        <script src="{% static 'todo/init.js' %}"></script>
    </head>
    <body>
        
    </body>
</html>

djlearn/todo/templates/todo/todolist.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>To-do list</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'todo/styles.css' %}">
        <script src="{% static 'todo/init.js' %}"></script>
    </head>
    <body>
        <script>
            const csrfToken = '{{ csrf_token }}'.split('value=')[0];
            function updateItem(element, item_id) {
                var xmlHttp = new XMLHttpRequest();
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                        element.innerText = element.innerText === '☐' ? '✔' : '☐';
                }
                xmlHttp.open("POST", "{% url 'todo:update' 'toggle' %}", true);
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&item_id=" + item_id);
            }
        </script>
        <h1>To-do list for {{ user.username }}</h1>
        {% for category in categories %}
        <fieldset>
            <legend>{{ category.name }}</legend>
            <ul>
                {% for item in category.todo_items %}
                <li>
                    {% if category.modify %}<button onclick="updateItem(this, {{ item.id }})">{% endif %}
                    {% if item.completed %}
                        ✔
                    {% else %}
                        ☐
                    {% endif %}
                    {% if category.modify %}</button>{% endif %}
                    &nbsp;
                    {% if item.name %}
                    {{ item.name }}
                    {% else %}
                    (No name)
                    {% endif %}
                    {% if item.description %}
                        <ul>
                            <li>{{ item.description }}</li>
                        </ul>
                    {% endif %}
                </li>
                {% empty %}
                    <li>No to-do items found.</li>
                {% endfor %}
            </ul>
        </fieldset>
        {% empty %}
            <p>No categories found.</p>
        {% endfor %}
        <a href="{% url 'todo:edit' user.id %}">Edit to-do list</a>
        <br>
        <a href="{% url 'todo:user' user.id %}">Back to profile</a>
    </body>
</html>

djlearn/todo/templates/todo/user.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Profile</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'todo/styles.css' %}">
        <script src="{% static 'todo/init.js' %}"></script>
    </head>
    <body>
        <script>
            const csrfToken = '{{ csrf_token }}'.split('value=')[0];
            function getFriendName() {
                return document.getElementById('add_friend').value;
            }
            function addFriend(friend_name) {
                var xmlHttp = new XMLHttpRequest();
                xmlHttp.open("POST", "{% url 'todo:update' 'addFriend' %}", true);
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4)
                        if (xmlHttp.status == 201) location.reload();
                        else if (xmlHttp.status == 404) alert("User not found. Make sure you use their username, not display name.");
                }
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&friend_id=" + friend_name);
            }
            function cancelFriendRequest(friend_id) {
                var xmlHttp = new XMLHttpRequest();
                xmlHttp.open("POST", "{% url 'todo:update' 'cancelFriendRequest' %}", true);
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                        location.reload();
                }
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&friend_id=" + friend_id);
            }
            function acceptFriendRequest(friend_id) {
                var xmlHttp = new XMLHttpRequest();
                xmlHttp.open("POST", "{% url 'todo:update' 'acceptFriend' %}", true);
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                        location.reload();
                }
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&friend_id=" + friend_id);
            }
            function rejectFriendRequest(friend_id) {
                var xmlHttp = new XMLHttpRequest();
                xmlHttp.open("POST", "{% url 'todo:update' 'declineFriend' %}", true);
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                        location.reload();
                }
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&user_id=" + {{ user.id }} + "&friend_id=" + friend_id);
            }
            function removeFriend(friend_id) {
                var xmlHttp = new XMLHttpRequest();
                if (confirm("Are you sure you want to remove this friend? You can always re-add them later.")) {
                    xmlHttp.open("POST", "{% url 'todo:update' 'removeFriend' %}", true);
                    xmlHttp.onreadystatechange = () => {
                        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                            location.reload();
                    }
                    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                    xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&user_id=" + {{ user.id }} + "&friend_id=" + friend_id);
                } else return;
            }
            function changePassword() {
                window.location.href = "{% url 'password_change' %}";
            }
            function logout() {
                if (confirm("Are you sure you want to log out?")) {
                    var xmlHttp = new XMLHttpRequest();
                    xmlHttp.open("POST", "{% url 'logout' %}", true);
                    xmlHttp.onreadystatechange = () => {
                        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                            window.location.href = xmlHttp.responseURL;
                    }
                    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                    xmlHttp.send("csrfmiddlewaretoken=" + csrfToken);
                }
            }
            function updateFriendPerms() {
                var xmlHttp = new XMLHttpRequest();
                var perms = document.getElementById('friend_perms').value;
                xmlHttp.open("POST", "{% url 'todo:update' 'setFriendPerms' %}", true);
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&user_id=" + {{ user.id }} + "&perms=" + perms);
            }
            function updateEveryonePerms() {
                var xmlHttp = new XMLHttpRequest();
                var perms = document.getElementById('everyone_perms').value;
                let cont = true;
                if (perms == "M") {
                    cont = confirm("Warning: Allowing everyone to modify your to-do lists can lead to unwanted changes. It is recommended to set this to 'View' or 'None'.");
                }
                if (cont) {
                    xmlHttp.open("POST", "{% url 'todo:update' 'setEveryonePerms' %}", true);
                    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                    xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&user_id=" + {{ user.id }} + "&perms=" + perms);
                }
            }
            function updateDisplayName() {
                var xmlHttp = new XMLHttpRequest();
                var display_name = document.getElementById('display_name').value;
                xmlHttp.open("POST", "{% url 'todo:update' 'setDisplayName' %}", true);
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                        location.reload();
                }
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&user_id=" + {{ user.id }} + "&display_name=" + display_name);
            }
            function setEmail() {
                email = prompt("Please enter your email address:");
                if (email != null) {
                    var xmlHttp = new XMLHttpRequest();
                    xmlHttp.open("POST", "{% url 'todo:update' 'setEmail' %}", true);
                    xmlHttp.onreadystatechange = () => {
                        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                            alert("Email updated successfully.");
                    }
                    xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                    xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&user_id=" + {{ user.id }} + "&email=" + email);
                }
            }
            function deleteUser() {
                if (!confirm("Are you sure you want to delete this user?")) return;
                if (!confirm("Are you really, really sure?")) return;
                if (!confirm("Are you absolutely, positively 100% sure? THERE IS NO GOING BACK AFTER YOU HIT CONFIRM.")) return;
                var xmlHttp = new XMLHttpRequest();
                xmlHttp.open("POST", "{% url 'todo:update' 'deleteUser' %}", true);
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4 && xmlHttp.status == 200) 
                        window.location.assign(xmlHttp.responseURL);
                }
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&user_id={{ user.id }}");
            }
            function createTeam() {
                let teamName = prompt("Enter a name for your new team:");
                if (teamName == null || teamName == "") return;
                var xmlHttp = new XMLHttpRequest();
                xmlHttp.open("POST", "{% url 'todo:update' 'createTeam' %}", true);
                xmlHttp.onreadystatechange = () => {
                    if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
                        window.location.assign(xmlHttp.responseURL);
                }
                xmlHttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                xmlHttp.send("csrfmiddlewaretoken=" + csrfToken + "&team_name=" + teamName);
            }
        </script>
        <h1>{{ user.display_name }}'s Profile</h1>
        <h5>({{user.username}})</h5>
        {% if self == user %}
        <p>
            <input id="display_name" placeholder="Display Name"><button onclick="updateDisplayName()">Set display name</button>
            <button onclick="logout()">Log out</button>
            <button onclick="changePassword()">Change Password</button>
            <button onclick="setEmail()">Set Email</button>
            <button onclick="deleteUser()">Delete User</button>
        </p>
        {% endif %}
        <h2><a href="{% url 'todo:todolist' user.id %}">To-Do List</a></h2>
        <h2>Teams</h2>
        <ul>
            {% for category in categories %}
            <li><a href="{% url 'todo:team' category.id %}">{{ category.name }}</a></li>
            {% empty %}
            <li>Not in any teams.</li>
            {% endfor %}
        </ul>
        <button onclick="createTeam()">Create New Team</button>
        {% if self == user %}
        <h2>Friends</h2>
        <input id="add_friend">
        <button onclick="addFriend(getFriendName())">Add Friend</button>
        <ul>
        {% for request in friend_requests %}
            <li>{{ request.display_name }}<button onclick="cancelFriendRequest({{ request.id }})">Cancel</button></li>
        {% empty %}
            <li>No outgoing friend requests.</li>
        {% endfor %}
        </ul>
        <ul>
        {% for request_inc in incoming_requests %}
            <li>{{ request_inc.display_name }}<button onclick="acceptFriendRequest({{ request_inc.id }})">Accept</button><button onclick="rejectFriendRequest({{ request_inc.id }})">Reject</button></li>
        {% empty %}
            <li>No incoming friend requests.</li>
        {% endfor %}
        </ul>
        <ul>
        {% for friend in friends %}
            <li><a href="{% url 'todo:user' friend.id %}">{{ friend.display_name }}</a><button onclick="removeFriend({{ friend.id }})">Remove</button></li>
        {% empty %}
            <li>No friends found.</li>
        {% endfor %}
        </ul>
        <label for="friend_perms">Friend Permissions:</label>
        <select id="friend_perms" name="friend_perms">
            <option value="P" {% if user.friend_perms == "P" %}selected{% endif %}>None</option>
            <option value="V" {% if user.friend_perms == "V" %}selected{% endif %}>View</option>
            <option value="M" {% if user.friend_perms == "M" %}selected{% endif %}>Modify</option>
        </select>
        <button onclick="updateFriendPerms()">Update</button>
        
        <label for="everyone_perms">Everyone Permissions:</label>
        <select id="everyone_perms" name="everyone_perms">
            <option value="P" {% if user.everyone_perms == "P" %}selected{% endif %}>None</option>
            <option value="V" {% if user.everyone_perms == "V" %}selected{% endif %}>View</option>
            <option value="M" {% if user.everyone_perms == "M" %}selected{% endif %}>Modify</option>
        </select>
        <button onclick="updateEveryonePerms()">Update</button>
        {% elif self %}
        {% if self in friends or self in incoming_requests or self in friend_requests %}
        <p><button disabled="" style="color: rgb(58, 58, 58);">Add Friend</button></p>
        {% else %}
        <p><button onclick="addFriend('{{ user.username }}')">Add Friend</button></p>
        {% endif %}
        {% endif %}
    </body>
</html>